.TH PTAR 1 "" "" "Commandes"
.SH NOM
ptar \- Listing et extraction d’archives TAR
.SH SYNOPSIS
.B ptar
.RI [ OPTION ]...[ FICHIER ]
.SH DESCRIPTION
Affiche le contenu (si aucun paramètre n'est fourni) ou, plus utile, extrait l'archive TAR nommée FICHIER, à partir du répertoire courant.
.SH OPTIONS
Aucune option n'est obligatoire.
.TP
.B \-x		
En plus de lister le contenu de l'archive TAR passée en paramètre, extrait son contenu (crée les répertoires, fichiers, définit les permissions, les propriétaires, les dates de modification, etc.)
.TP
.B \-l		
Listing détaillé. Par défaut, ptar n'affiche que les noms des répertoires et fichiers. Avec l'option -l, ptar affiche, séparés par un espace à chaque fois:
- les permissions sous la forme drwxr-xr-x (comme dans la sortie de ls -l)
- l'uid et le gid du fichier, sous la forme 1001/1001
- la taille du fichier (en décimal)
- la date de modification, sous la forme 2016-10-13 16:44:12
- le nom du fichier ou du répertoire (suivi d’un / si répertoire)
- si le fichier est un lien symbolique, "-> destination"
.TP
.BI \-p	 NBTHREADS
Utilise NBTHREADS threads pour réaliser les écritures en parallèle.
.TP
.B \-z		
L'archive passée en paramètre est compressée avec gzip; demande à ptar de la décompresser avant de la traiter. ptar chargera dynamiquement la bibliothèque zlib (avec dlopen) pour effectuer la décompression.
.PP
Toutes les options peuvent être combinées.
.SH VALEUR DE RETOUR
ptar s’arrête en renvoyant la valeur de retour 0 si tous les traitements se sont déroulés avec succès; 1 sinon.
.SH EXEMPLE
.TP
ptar \-lxzp 8 fichier.tar.gz
Liste le contenu détaillé de fichier.tar.gz (une archive tar compressée avec gzip) et extrait son contenu dans le répertoire courant. L'extraction se fait en utilisant 8 threads.
.SH VOIR AUSSI
.BR tar (1),
.BR tar (5),
.BR zlib (3)
